variable "region"{}
variable "aws_profile"{}
variable "key_name"{}
variable "instance_class"{}
variable "aws_subnet"{}
variable "ami_type"{}
variable "security_group"{}
variable "S3"{}
variable "private_keypath"{}
